StoryTeller.UI/ViewModels/SearchViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace StoryTeller.ViewModels
{
    public class SearchViewModel
    {
        public string SearchText { get; set; }
    }
}

StoryTeller.UI/Controllers/StoryController.cs
using Microsoft.AspNet.Identity;
using Microsoft.AspNet.Identity.EntityFramework;
using Microsoft.AspNet.SignalR;
using StoryTeller.Common;
using StoryTeller.Common.Helpers;
using StoryTeller.Common.Hubs;
using StoryTeller.Domain.Common;
using StoryTeller.Domain.Models;
using StoryTeller.Models;
using StoryTeller.Models.ViewModels;
using StoryTeller.ViewModels;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace StoryTeller.Controllers
{
    [RequireHttps]
    public class StoryController : Controller
    {
        private ApplicationDbContext db;
        private UserManager<ApplicationUser> manager;
        private IHubContext likeHub;
        private IHubContext votingHub;

        public StoryController()
        {
            db = new ApplicationDbContext();
            manager = new UserManager<ApplicationUser>(new UserStore<ApplicationUser>(db));
            likeHub = GlobalHost.ConnectionManager.GetHubContext<LikesHub>();
            votingHub = GlobalHost.ConnectionManager.GetHubContext<VotingHub>();
        }

        [HttpPost]
        public JsonResult IsTitleExists(string Title)
        {
            return Json(!db.Stories.Any(x => x.Title == Title));
        }

        // GET: Stories/Details/5
        [System.Web.Mvc.Authorize]
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            var story = await db.Stories.FindAsync(id);

            if (story == null)
            {
                return HttpNotFound();
            }

            return View(story);
        }

        // GET: Stories/Create
        [System.Web.Mvc.Authorize]
        public ActionResult Create()
        {
            ViewBag.ID = new SelectList(db.Votings, "ID", "ID");
            return View();
        }

        [HttpGet]
        public ActionResult CreateNewChapter(int storyId)
        {
            var story = db.Stories.Find(storyId);
            var userChapter = story.ChaptersToVote.FirstOrDefault(x => x.Chapter.User == this.CurrentUser);

            if (userChapter != null)
            {
                return PartialView("~/Views/Story/Partials/_ChapterCreate.cshtml", new ChapterCreateViewModel() { StoryId = storyId, Text = userChapter.Chapter.Text, MaxChapterLength = (int)story.MaxChapterLength });
            }

            return PartialView("~/Views/Story/Partials/_ChapterCreate.cshtml", new ChapterCreateViewModel() { StoryId = storyId, MaxChapterLength = (int)story.MaxChapterLength });
        }

        [HttpPost]
        public async Task<ActionResult> CreateNewChapter(ChapterCreateViewModel chapter)
        {
            if (ModelState.IsValid)
            {
                var story = await db.Stories.FindAsync(chapter.StoryId);
                var userChapter = story.ChaptersToVote.FirstOrDefault(x => x.Chapter.User == this.CurrentUser);
                var isAdded = false;
                ChapterToVote chapterToVote = null;

                if (userChapter != null)
                {
                    userChapter.Chapter.Text = chapter.Text;
                }
                else
                {
                    chapterToVote = new ChapterToVote() { Chapter = new Chapter() { Text = chapter.Text, Created = DateTime.Now, User = CurrentUser } };
                    story.ChaptersToVote.Add(chapterToVote);
                    isAdded = true;
                }

                await db.SaveChangesAsync();

                if(isAdded == true)
                {
                    var chapterPartialView = PartialViewParsesr.RenderPartialToString("~/Views/Story/Partials/_ChapterToVote.cshtml", chapterToVote, this.ControllerContext);
                    votingHub.Clients.All.AddChapterToVote(chapterPartialView);
                }

                return PartialView("~/Views/Story/Partials/_Thanks.cshtml");
            }

            return PartialView("~/Views/Story/Partials/_ChapterCreate.cshtml", chapter);
        }

        public async Task<ActionResult> GetVotingPartial(int storyID)
        {
            var story = await db.Stories.FindAsync(storyID);

            if (story != null)
            {
                VotingSectionViewModel votingSectionVM;
                if (!story.IsFull)
                {
                    var timerVM = new TimerViewModel();
                    var votingChaptersVM = new VotingChaptersViewModel();
                    votingSectionVM = new VotingSectionViewModel(votingChaptersVM, timerVM);

                    votingChaptersVM.ChaptersToVote = setChaptersToVoteViewModel(story.ChaptersToVote.ToList());

                    if (story.IsVoting == true)
                    {
                        setStoryVoting(votingSectionVM, timerVM, story);
                    }
                    else
                    {
                        setStoryNotVoting(votingSectionVM, timerVM, story);
                    }

                    setUserAddedChapter(votingSectionVM, storyID);
                }
                else
                {
                    votingSectionVM = new VotingSectionViewModel();
                }

                votingSectionVM.IsFull = story.IsFull;

                return PartialView("~/Views/Story/Partials/_StoryVotingSection.cshtml", votingSectionVM);
            }

            return HttpNotFound();
        }

        public async Task<ActionResult> GetStoryDetails(int storyID)
        {
            var story = await db.Stories.FindAsync(storyID);
            return PartialView("~/Views/Story/Partials/_StoryDetails.cshtml", story);
        }

        private void setUserAddedChapter(VotingSectionViewModel votingSectionVM, int storyID)
        {
            var chapter = getUserChapterToVoteAsync(storyID).Result;
            if (chapter != null)
            {
                votingSectionVM.AlreadyAddedChapter = true;
            }
            else
            {
                votingSectionVM.AlreadyAddedChapter = false;
            }
        }

        private void setStoryNotVoting(VotingSectionViewModel votingSectionVM, TimerViewModel timerVM, Story story)
        {
            votingSectionVM.IsVoting = false;

            timerVM.CssClass = "NotVoting";
            timerVM.TimerText = "Time before voting";
            timerVM.Distance = (int)(story.NextVotingDate - DateTime.Now).Value.TotalMilliseconds;
            timerVM.CountDownDate = (DateTime)story.NextVotingDate;
        }

        private void setStoryVoting(VotingSectionViewModel votingSectionVM, TimerViewModel timerVM, Story story)
        {
            votingSectionVM.IsVoting = true;
            timerVM.CssClass = "text-danger";
            timerVM.TimerText = "Time before voting end";
            timerVM.Distance = (int)(story.EndOfVotingsDate - DateTime.Now).Value.TotalMilliseconds;
            timerVM.CountDownDate = (DateTime)story.EndOfVotingsDate;
        }

        [HttpGet]
        public async Task<ActionResult> VoteChapter(int storyID, int chapterID)
        {
            var story = await db.Stories.FindAsync(storyID);
            var chapter = story.ChaptersToVote.ToList().Find(x => x.ID == chapterID);
            List<Like> allLikes = new List<Like>();

            foreach (var chapterToVote in story.ChaptersToVote)
                allLikes.AddRange(chapterToVote.Likes);

            var userLike = allLikes.FirstOrDefault(x => x.User == CurrentUser);

            if (userLike != null)
            {
                var chapterToVote = userLike.ChapterToVote;
                db.Likes.Remove(userLike);
            }

            chapter.Likes.Add(new Like() { Created = DateTime.Now, User = CurrentUser });
            await db.SaveChangesAsync();

            return Json(new { success = true }, JsonRequestBehavior.AllowGet);
        }

        private List<ChapterToVote> setChaptersToVoteViewModel(List<ChapterToVote> chaptersToVote)
        {
            foreach (var chapter in chaptersToVote)
            {
                if (chapter.Likes.ToList().Exists(x => x.User == CurrentUser))
                    chapter.voteBtnStyle = "btnVoted";
                else
                    chapter.voteBtnStyle = "btnNotVoted";
            }

            return chaptersToVote;
        }

        private async Task<ChapterToVote> getUserChapterToVoteAsync(int storyID)
        {
            var story = await db.Stories.FindAsync(storyID);
            var chapter = story.ChaptersToVote.Where(x => x.Chapter.User == CurrentUser).FirstOrDefault();

            return chapter;
        }

        // POST: Stories/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Exclude = "Picture")]StoryViewModel storyVM)
        {
            if (ModelState.IsValid)
            {
                byte[] imageData = FileUploader.GetFile("Photo", Request);

                var newStory = new Story()
                {
                    Title = storyVM.Title,
                    Created = DateTime.Now,
                    IsClosed = false,
                    IsVoting = false,
                    MaxChaptersNumber = storyVM.MaxChaptersNumber,
                    MaxChapterLength = storyVM.MaxChapterLength,
                    NextVotingDate = DateTime.Now.AddMinutes((double)storyVM.TimeBetweenVotings),
                    TimeBetweenVotings = storyVM.TimeBetweenVotings,
                    TimeForVotings = storyVM.TimeForVotings,
                    Creator = CurrentUser,
                    ViewsCount = 0,
                    Picture = imageData

StoryTeller.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - StoryTeller</title>
    @*<link href="~/Content/bootstrap.min.css" rel="stylesheet" />*@
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @*<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-confirm/3.3.0/jquery-confirm.min.css">*@
</head>
<body>


    <nav class="navbar navbar-default navbar-fixed-top">
        <div class="container ">
            <div class="navbar-header">
                @Html.ActionLink("Stories", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>

            @Html.Action("Search", "Story")

            @Html.Partial("_LoginPartial")

        </div>
    </nav>

    @if (User.Identity.IsAuthenticated)
    {
        <button style="text-align:center" class="btn btn-lg btn-info " id="bottom-right-button" onclick="location.href='@Url.Action("Create", "Story")'">
            Write your story <span class="glyphicon glyphicon-pencil"></span>
        </button>
    }

    <div class="container body-content">
        @RenderBody()
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
    @Scripts.Render("~/bundles/bootstrap")
    @Scripts.Render("~/bundles/signalr")
    <script src="~/signalr/hubs"></script>
    @Scripts.Render("~/bundles/custom")
    @RenderSection("scripts", required: false)
</body>
</html>

StoryTeller.UI/Views/Shared/_SearchForm.cshtml
@model StoryTeller.ViewModels.SearchViewModel

@using (Html.BeginForm("SearchSubmit", "Story", FormMethod.Post, new { id = "formSearchStories" , @class = "navbar-form navbar-left" }))
{
        <div class="form-group">
            @Html.EditorFor(model => model.SearchText, new { htmlAttributes = new { @class = "form-control", @id = "search-input", @placeholder = "Search for stories...", @type="text" } })
        </div>
        <button type="submit" class="btn btn-default">
            <span class="glyphicon glyphicon-search"></span>
        </button>
}

StoryTeller.UI/Views/Shared/_UserDialog.cshtml
@model StoryTeller.Domain.Models.ApplicationUser

<div class="modal fade" id="userModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true"></button>
                <h4 class="modal-title" id="myModalLabel">@Model.StoryTellerName</h4>
            </div>
            <div class="modal-body">
                <center>
                    <img src="@Url.Action("UserPhoto", "Account", new {userID = Model.Id } )" name="aboutme" width="140" height="140" border="0" class="img-circle">
                    <h3 class="media-heading">@Model.Email</h3>
                    <span><strong>Stats: </strong></span>
                    <span class="label label-warning">Stories: @Model.Stories.Count()</span>
                    <span class="label label-info">Chapters:  @Model.Chapters.Count()</span>
                    @*<span class="label label-info">Microsoft Office</span>
                    <span class="label label-success">Windows XP, Vista, 7</span>*@
                </center>
                <hr>
                <center>
                    <p class="text-left">
                        <strong>Bio: </strong>
                        @Model.Bio
                    </p>
                    <br>
                </center>
            </div>
            <div class="modal-footer">
                <center>
                    <button type="button" class="btn btn-default" data-dismiss="modal" id="closeUserDetails">Close</button>
                </center>
            </div>
        </div>
    </div>
</div>